### PR TITLE
feat: Implemented a feedback form 

### PR DESCRIPTION
**Pull request by ssk090**
## Pull Request Summary
- Implemented a basic feedback form in the about page
- fixes: https://github.com/aadeshkulkarni/first-issues/issues/7
image
image

### CODE REVIEW

**Comment by aadeshkulkarni** [comment]
Nicely done. 

Here are few issues:
- It should be `FirstIssues` instead of `Good First issues`
- The feedback form is visible after scrolling down. Can we take it up, may be a two column layout for desktop and something else for mobile ?
- Add a feedback link to the home page below Browser by language section.

Screenshot 2024-06-28 at 3 56 43 PM

@KrupaPanchal2527  - Please take a second pass of review, add suggestions, if any.

**Comment by KrupaPanchal2527** [comment]
Overall looks really good. Few points from my end - 
1. Let's show the feedback form submission message in an alert/toast which will be dismissed automatically after few seconds.
image

2. Disable the `Submit` button while feedback is being saved to the server - this way we can avoid 
3. I would also like to accept `email` as an input - this way it would enable us to reach out to people in case further discussion/suggestions are needed.

**Comment by ssk090** [comment]
on it 🫡

**Comment by ssk090** [comment]
- Updated the feedback form with email field.
- Created a new route for the feedback form. (You can go to /feedback to access the form)
- Added toast message for the feedback submit button.

image

**Comment by ssk090** [comment]
Hey @KrupaPanchal2527 / @aadeshkulkarni, I have updated the branch according to the required changes. Do let me know if any further changes are required. Thank You!

**Comment by KrupaPanchal2527** [comment]
@ssk090 Changes looks great. Thanks for getting this in. 
I think the feedback form will help us get suggestions and feedback for our application which will be a really good thing!

I have made some minor change -
- Moved email field to new line
- Renamed the feedback form file name to follow the other files naming convention

**Review by KrupaPanchal2527 — APPROVED** [review]

**Comment by ssk090** [comment]
Thank you for the feedback! I'm glad the changes look good to you.

**Pull request merged**
