### PR TITLE
Soring based on ascending order

### PR DESCRIPTION
**Pull request by Amar995**
#### ℹ️ Repository information

**The repository has**:

- [ ] At least three issues with the `good first issue` label.
- [ ] At least 10 contributors.
- [ ] Detailed setup instructions for the project.
- [ ] CONTRIBUTING.md
- [ ] Actively maintained.

### CODE REVIEW

**Comment by Amar995** [comment]
@aadeshkulkarni sorry for multiple try .check it final  time

Thanks

**Comment by Amar995** [comment]
@aadeshkulkarni Hi any update?

**Comment by aadeshkulkarni** [comment]
Can you transform everything into lowercase, then sort in ascending order please ? 

This will ensure the order is consistent.

**Comment by Amar995** [comment]
@aadeshkulkarni I will

**Pull request closed without merging**
